version: '3.8'

services:

  redis:
    image: redis:7
    container_name: redis_delivery
    ports:
      - "6379:6379"
    networks:
      - delivery_network

  api:
    build: .
    container_name: delivery_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - delivery_network

networks:
  delivery_network:
